### PR TITLE
Update README with new stuff and use await in gateway

### PR DESCRIPTION
**Pull request by Yardanico**
Changed asyncCheck and waitFor to await in the startSession, also added runForever because otherwise it wouldn't really run for me since startSession starts the session and then returns, so the bot will basically exit since there's nothing to do after "waitFor"

### CODE REVIEW

**Comment by krisppurg** [comment]
The asyncCheck in the for loop is necessary for sharding, because theres probably a bug on nim or something like that when you use `await`.

**Comment by Yardanico** [comment]
@krisppurg what bug exactly? As far as I can see startSession really doesn't run for long so it'll return in a short amount of time

**Comment by krisppurg** [comment]
(see edited message) try setting the shards to at least 2 and see the issue.

**Comment by krisppurg** [comment]
I actually didn't know CatchableError existed in Nim, huh.

**Pull request merged**
