### PR TITLE
close http client

### PR DESCRIPTION
**Pull request by t8m8**
HTTP client should be closed because it consumes file descriptor

### CODE REVIEW

**Comment by krisppurg** [comment]
Client should close in line 248, I've had issues in the past where there were problems with client.close before parsing json and error handling.

**Comment by t8m8** [comment]
I see. Anyway, since I'm using a defer statement, it's equivalent to closing with line 248, right?

**Comment by t8m8** [comment]
I understood. I moved it to line 248.

**Comment by krisppurg** [comment]
@t8m8 Sorry, for delay

Double checking have you tested this?

And could you try doing a ratelimit test on this? I've in the past had issues with ratelimiting where client.close was the issue, so im not 100% sure if it might cause issues.

And also try testing `getGuildAuditLogs(...)`, since audit log data is known to be chunky depending on how much entries there are.

Just make sure ratelimits are working fine as usual and other endpoints.

**Comment by t8m8** [comment]
@krisppurg I've been testing it and so far it seems to be working fine.

For my information, when you had issues with ratelimiting before, what kind of issues did you have?

**Comment by krisppurg** [comment]
No need to worry about those issues, removing client.close() was the solution. I believe this was in May 2020

**Pull request merged**
