### PR TITLE
Add components to message editing

### PR DESCRIPTION
**Pull request by ire4ever1190**
Allows `editMessage` to edit message components

### CODE REVIEW

**Review by krisppurg — CHANGES_REQUESTED** [review]
Lines should break at 80-81 characters.

**Comment by ire4ever1190** [comment]
Like this instead?
```nim
proc editMessage*(api: RestApi, channel_id, message_id: string;
        content = ""; tts = false; flags = none(int);
        embeds = newSeq[Embed](), components = newSeq[MessageComponent]()): 
            Future[Message] {.async.} =
```

**Comment by krisppurg** [comment]
> Like this instead?
> ```nim
> proc editMessage*(api: RestApi, channel_id, message_id: string;
>         content = ""; tts = false; flags = none(int);
>         embeds = newSeq[Embed](), components = newSeq[MessageComponent]()): 
>             Future[Message] {.async.} =
> ```

Sort of

```nim
proc editMessage*(api: RestApi, channel_id, message_id: string;
        content = ""; tts = false; flags = none(int);
        embeds = newSeq[Embed](),
        components = newSeq[MessageComponent]()): Future[Message] {.async.} =
```

**Comment by ire4ever1190** [comment]
Think I copied my example wrong before somehow.

Code already looks like this so is it fine?
```nim
proc editMessage*(api: RestApi, channel_id, message_id: string;
        content = ""; tts = false; flags = none(int);
        embeds = newSeq[Embed](),
        components = newSeq[MessageComponent]()): Future[Message] {.async.} =  # 77 chars longs
```

**Comment by krisppurg** [comment]
Its alright

**Comment by krisppurg** [comment]
Any updates?

**Comment by ire4ever1190** [comment]
Every line is under 80 characters and it works so is ready for merge

**Pull request merged**
