### PR TITLE
Add forum fields and media channel

### PR DESCRIPTION
**Pull request by bit0r1n**

### CODE REVIEW

**Review by ire4ever1190 — APPROVED** [review]
Nice, looks good to me :+1: 

[Related discord API commit](https://github.com/discord/discord-api-docs/commit/612eadc324a50e24e8307b6c2ed1fb7a98606e8a)

**Comment by bit0r1n** [comment]
This is just same as forum, which fields was not added earlier anyway (`default_*`)
<details>
   <summary>Output of /channels/:id with type=16</summary>
{
  id: '1120708983754326108',
  type: 16,
  last_message_id: '1120742401133269023',
  flags: 0,
  guild_id: '925061751211450380',
  name: 'старый-канал',
  parent_id: null,
  rate_limit_per_user: 0,
  topic: null,
  position: 0,
  permission_overwrites: [Array],
  nsfw: false,
  available_tags: [],
  default_reaction_emoji: null,
  default_sort_order: null,
  default_forum_layout: 2,
  template: ''
}
  </details>

**Comment by krisppurg** [comment]
> This is just same as forum, which fields was not added earlier anyway (`default_*`, `available_tags`)
> <details>
>    <summary>Output of /channels/:id with type=16</summary>
> {
>   id: '1120708983754326108',
>   type: 16,
>   last_message_id: '1120742401133269023',
>   flags: 0,
>   guild_id: '925061751211450380',
>   name: 'старый-канал',
>   parent_id: null,
>   rate_limit_per_user: 0,
>   topic: null,
>   position: 0,
>   permission_overwrites: [Array],
>   nsfw: false,
>   available_tags: [],
>   default_reaction_emoji: null,
>   default_sort_order: null,
>   default_forum_layout: 2,
>   template: ''
> }
>   </details>

Should add the missing fields to GuildChannel then

**Comment by bit0r1n** [comment]
okay, I will add with this pr

**Review by krisppurg — APPROVED** [review]

**Pull request merged**
